---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/send-status-email":
    post:
      summary: Send availability status email
      tags:
      - AvailabilityStatusEmail
      description: Send an email with the current availability status to the user
      responses:
        '200':
          description: email sent
        '401':
          description: unauthorized
        '500':
          description: internal server error
  "/api/v1/availability_status":
    post:
      summary: Create or update availability status
      tags:
      - AvailabilityStatus
      parameters: []
      responses:
        '200':
          description: availability status updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                availabilityStatus:
                  type: string
                time:
                  type: string
                location:
                  type: string
              required:
              - availabilityStatus
    get:
      summary: List availability statuses for a specific date
      tags:
      - AvailabilityStatus
      parameters:
      - name: date
        in: query
        example: '2024-11-06'
        description: Date in YYYY-MM-DD format
        schema:
          type: string
      responses:
        '200':
          description: statuses found
        '404':
          description: no statuses found
        '500':
          description: server error
  "/api/v1/users/register":
    post:
      summary: User Registration
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user registered
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
              - name
              - email
              - password
  "/api/v1/users/login":
    post:
      summary: User Login
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user logged in
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/users/logout":
    post:
      summary: User Logout
      tags:
      - Users
      responses:
        '200':
          description: logout successful
        '401':
          description: unauthorized - no token present
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
